DROP TABLE IF EXISTS Friendships;

DROP TABLE IF EXISTS Account_photo;

DROP TABLE IF EXISTS Phones;

DROP TABLE IF EXISTS Accounts_in_groups;

DROP TABLE IF EXISTS _Groups;

DROP TABLE IF EXISTS Passwords;

DROP TABLE IF EXISTS Accounts;

DROP TABLE IF EXISTS Roles;
